server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true

  datasource:
    password: asdf/1234
    username: admin
    url: jdbc:mysql://localhost:3306/shopping

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type: TRACE

